name: firestore_scripts
description: Firestore normalization and utility scripts
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_core: ^2.27.0